**Nomor 1**
Terdapat sebuah robot yang berada pada ruang 3D dengan koordinat mengikuti aturan tangan kanan dengan konfigurasi tersebut. Robot terdiri dari tiga buah sendi yang secara berurutan berjenis sendi putar, sendi prismatik dan sendi putar. Tentukan titik akhir dari robot dengan menggunakan Denavit Hartenberg apabila memiliki parameter DH seperti yang ditunjukkan pada tabel. Buatlah kode programnya dan penjelasan secukupnya. Informasi seputar DH bisa dicari di Google.

In [ ]:
from numpy import sin, cos, pi, array, eye, dot
from numpy.linalg import multi_dot

In [ ]:
def TransZ(de, en=1):
    Di = [0. for ka in range(en)]
    for i in range(0, en):
        Di[i] = array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, de[i]],
                      [0, 0, 0, 1]])
    return Di

In [ ]:
def TransX(aa, en=1):
    Ai = [0. for ka in range(en)]
    for i in range(0, en):
        Ai[i] = array([[1, 0, 0, aa[i]],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])
    return Ai

In [ ]:
def RotZ(te, en=1):
    Ti = [0. for ka in range(en)]
    for i in range(0, en):
        Ti[i] = array([[cos(te[i]), -sin(te[i]), 0, 0],
                      [sin(te[i]), cos(te[i]), 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])
    return Ti

In [ ]:
def RotX(aa, en=1):
    Ai = [0. for ka in range(en)]
    for i in range(0, en):
        Ai[i] = array([[1, 0, 0, 0],
                      [0, cos(aa[i]), -sin(aa[i]), 0],
                      [0, sin(aa[i]), cos(aa[i]), 0],
                      [0, 0, 0, 1]])
    return Ai

In [ ]:
def Trans(rotx, rotz, transx, transz, en=1):
    TT = [0. for ka in range(en)]
    for i in range(0, en):
        TT[i] = multi_dot([rotx[i], transx[i], rotz[i], transz[i]])
        print("Trans ke-",i," = ",TT[i])
    return TT

In [ ]:
def TransTotal(TT, en=1):
    TransTot = eye(4)
    for i in range(0, en):
        TransTot = dot(TransTot, TT[i])
        print("Perkalian Trans ke-",i," = ",TransTot)
    return TransTot

In [ ]:
n = int(input("Tentukan jumlah joint: "))
d = [0. for k in range(n)]
a = [0. for k in range(n)]
t = [0. for k in range(n)]
alp = [0. for k in range(n)]
print("Jumlah joint = ",n)
for j in range(0, n):
    a[j] = float(input("\nPanjang link ke-%i ($a_%i$): "%(j+1,j+1)))
    d[j] = float(input("Panjang d ke-%i: "%(j+1)))
    t[j] = float(input("Sudut $\(theta)$ ke-%i: "%(j+1)))
    t[j] = t[j] / 180 * pi #diubah ke radian
    alp[j] = float(input("Sudut $\(alpha)$ ke-%i: "%(j+1)))
    alp[j] = alp[j] / 180 * pi #diubah ke radian
print("Theta i = ", t)
tz = TransZ(d, n)
tx = TransX(a, n)
rz = RotZ(t, n)
rx = RotX(alp, n)
Tr = Trans(rx, tx, rz, tz, n)
T = TransTotal(Tr, n)
P = [T[0,3], T[1,3], T[2,3]]
print("\n=================================================")
print("Trans Z = ", tz)
print("Trans X = ", tx)
print("Rot Z = ", rz)
print("Rot X = ", rx)
print("Trans Total = ", T)
print("=================================================\n")
print("Posisi end effector = ", P)

Tentukan jumlah joint: 3
Jumlah joint =  3

Panjang link ke-1 ($a_1$): 0
Panjang d ke-1: 10
Sudut $\(theta)$ ke-1: 30
Sudut $\(alpha)$ ke-1: 0

Panjang link ke-2 ($a_2$): 0
Panjang d ke-2: 7.5
Sudut $\(theta)$ ke-2: 0
Sudut $\(alpha)$ ke-2: 90

Panjang link ke-3 ($a_3$): 0
Panjang d ke-3: 3.75
Sudut $\(theta)$ ke-3: 45
Sudut $\(alpha)$ ke-3: 0
Theta i =  [0.5235987755982988, 0.0, 0.7853981633974483]
Trans ke- 0  =  [[ 0.8660254 -0.5        0.         0.       ]
 [ 0.5        0.8660254  0.         0.       ]
 [ 0.         0.         1.        10.       ]
 [ 0.         0.         0.         1.       ]]
Trans ke- 1  =  [[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  6.1232340e-17 -1.0000000e+00 -7.5000000e+00]
 [ 0.0000000e+00  1.0000000e+00  6.1232340e-17  4.5924255e-16]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
Trans ke- 2  =  [[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.