**Soal 1**

P awal = (20,30,10), P akhir diposisi apa jika berputar sebesar 15 derajat mengelilingi sumbu y --> gunakan metode rotation matrix 3D

In [ ]:
import numpy as np

theta = 15.0
x = 20
y = 30
z = 10

P = np.array([[x],
              [y],
              [z]])
print("P = \n",P)
theta = theta / 180 * np.pi
print("Theta dalam radian = ",theta)
rot = np.array ([[np.cos(theta), 0, np.sin(theta)],
                [0, 1, 0],
                [-np.sin(theta), 0, np.cos(theta)]])
print("Matriks rotasi: \n", rot)
P2 = rot.dot(P)
x2 = P2 [0,0]
y2 = P2 [1,0]
z2 = P2 [2,0]

print("P' = \n", P2)
print("x' = ", x2)
print("y' = ", y2)
print("z' = ", z2)

P = 
 [[20]
 [30]
 [10]]
Theta dalam radian =  0.2617993877991494
Matriks rotasi: 
 [[ 0.96592583  0.          0.25881905]
 [ 0.          1.          0.        ]
 [-0.25881905  0.          0.96592583]]
P' = 
 [[21.90670698]
 [30.        ]
 [ 4.48287736]]
x' =  21.906706976806575
y' =  30.0
z' =  4.482877360840268



**Soal 2**

P awal = (1,2,3), P akhir jika berotasi dengan urutan:

    - mengelilingi sumbu z sebesar 20 derajat,
    - mengelilingi sumbu x sebesar 10 derajat
    - mengelilingi sumbu y sebesar 30 derajat
    P akhir = ? --> gunakan metode rotation matrix 3D.

In [ ]:
import numpy as np
print("ROTASI 1")
psi = 20.0
x = 1
y = 2
z = 3

P = np.array([[x],
              [y],
              [z]])
print("P = \n",P)
psi = psi / 180 * np.pi
print("Psi dalam radian = ",psi)
rot = np.array ([[np.cos(psi), 0, -np.sin(psi)],
                [np.sin(psi), np.cos(psi), 0],
                [0, 0, 1]])
print("Matriks rotasi pertama: \n", rot)
P2 = rot.dot(P)
x2 = P2 [0,0]
y2 = P2 [1,0]
z2 = P2 [2,0]

print("P' = \n", P2)
print("x' = ", x2)
print("y' = ", y2)
print("z' = ", z2)
print("\n")


print("ROTASI 2")
print("Nilai P baru ",[x2, y2, z2])
phi = 10.0
P = np.array([[x],
              [y],
              [z]])
print("P = \n",P)
phi = phi / 180 * np.pi
print("Phi dalam radian = ",phi)
root = np.array ([[1, 0, 0],
                [0, np.cos(phi),-np.sin(phi)],
                [0, np.sin(phi), np.cos(phi)]])
print("Matriks rotasi kedua: \n", root)
P3 = root.dot(P2)
x3 = P3 [0,0]
y3 = P3 [1,0]
z3 = P3 [2,0]

print("P2 = \n", P)
print("x' = ", x3)
print("y' = ", y3)
print("z' = ", z3)
print("\n")

print("ROTASI 3")
print("Nilai P baru ",[x3, y3, z3])
theta = 30.0
P = np.array([[x],
              [y],
              [z]])
print("P = \n",P)
theta = theta / 180 * np.pi
print("Phi dalam radian = ",theta)
rooot = np.array ([[np.cos(theta), 0, np.sin(theta)],
                [0, 1, 0],
                [-np.sin(theta),0 , np.cos(theta)]])
print("Matriks rotasi ketiga: \n", rooot)
P4 = rooot.dot(P3)
x4 = P4 [0,0]
y4 = P4 [1,0]
z4 = P4 [2,0]

print("P2 = \n", P)
print("x' = ", x4)
print("y' = ", y4)
print("z' = ", z4)

ROTASI 1
P = 
 [[1]
 [2]
 [3]]
Psi dalam radian =  0.3490658503988659
Matriks rotasi pertama: 
 [[ 0.93969262  0.         -0.34202014]
 [ 0.34202014  0.93969262  0.        ]
 [ 0.          0.          1.        ]]
P' = 
 [[-0.08636781]
 [ 2.22140538]
 [ 3.        ]]
x' =  -0.08636780919109777
y' =  2.2214053848974857
z' =  3.0


ROTASI 2
Nilai P baru  [-0.08636780919109777, 2.2214053848974857, 3.0]
P = 
 [[1]
 [2]
 [3]]
Phi dalam radian =  0.17453292519943295
Matriks rotasi kedua: 
 [[ 1.          0.          0.        ]
 [ 0.          0.98480775 -0.17364818]
 [ 0.          0.17364818  0.98480775]]
P2 = 
 [[1]
 [2]
 [3]]
x' =  -0.08636780919109777
y' =  1.6667127126293209
z' =  3.3401662559835783


ROTASI 3
Nilai P baru  [-0.08636780919109777, 1.6667127126293209, 3.3401662559835783]
P = 
 [[1]
 [2]
 [3]]
Phi dalam radian =  0.5235987755982988
Matriks rotasi ketiga: 
 [[ 0.8660254  0.         0.5      ]
 [ 0.         1.         0.       ]
 [-0.5        0.         0.8660254]]
P2 = 
 [[1]

In [ ]:
import numpy as np

psi = 20.0
phi = 10.0
theta = 30.0
x = 1
y = 2
z = 3
P = np.array([[x],
              [y],
              [z]])
print("P = \n",P)
print("\n")
psi = psi / 180 * np.pi
print("Psi dalam radian = ",psi)
phi = phi / 180 * np.pi
print("Phi dalam radian = ",phi)
theta = theta / 180 * np.pi
print("theta dalam radian = ",theta)
print("\n")
rot_X=np.array ([[1, 0, 0],
                [0, np.cos(phi), -np.sin(phi)],
                [0, np.sin(phi), np.cos(phi)]])

rot_Y=np.array ([[np.cos(theta), 0, np.sin(theta)],
                [0, 1, 0],
                [-np.sin(theta), 0, np.cos(theta)]])

rot_Z=np.array([[np.cos(psi), -np.sin(psi), 0],
                [np.sin(psi), np.cos(psi), 0],
                [0, 0, 1]])
print("Matriks rotasi X: \n", rot_X)
print("Matriks rotasi X: \n", rot_Y)
print("Matriks rotasi X: \n", rot_Z)
print("\n")

rot_akhir=rot_Y.dot(rot_X).dot(rot_Z)
print("Matriks rotasi akhir: \n", rot_akhir)

P2 = rot_akhir.dot(P)
x2 = P2 [0,0]
y2 = P2 [1,0]
z2 = P2 [2,0]

print("P' = \n", P2)
print("x' = ", x2)
print("y' = ", y2)
print("z' = ", z2)

P = 
 [[1]
 [2]
 [3]]


Psi dalam radian =  0.3490658503988659
Phi dalam radian =  0.17453292519943295
theta dalam radian =  0.5235987755982988


Matriks rotasi X: 
 [[ 1.          0.          0.        ]
 [ 0.          0.98480775 -0.17364818]
 [ 0.          0.17364818  0.98480775]]
Matriks rotasi X: 
 [[ 0.8660254  0.         0.5      ]
 [ 0.         1.         0.       ]
 [-0.5        0.         0.8660254]]
Matriks rotasi X: 
 [[ 0.93969262 -0.34202014  0.        ]
 [ 0.34202014  0.93969262  0.        ]
 [ 0.          0.          1.        ]]


Matriks rotasi akhir: 
 [[ 0.84349327 -0.21461018  0.49240388]
 [ 0.33682409  0.92541658 -0.17364818]
 [-0.41841204  0.31232456  0.85286853]]
P' = 
 [[1.89148454]
 [1.66671271]
 [2.76484266]]
x' =  1.891484543889115
y' =  1.6667127126293209
z' =  2.7648426634780496
