## Tugas Rotation Matrix 2D
---
- Budi Ihsan Daulay
- Hutomo Khairinas
- Panji Bintoro
- Wanda Yusuf Alvian
---
### Rumus
$$
\begin{bmatrix} 
{x}' \\ {y}' 
\end{bmatrix}
=
\begin{bmatrix} 
\cos \theta & -\sin \theta 
\\ \sin\theta & \cos\theta 
\end{bmatrix} 
\begin{bmatrix} x \\ y \end{bmatrix}
$$

### 1
P awal
$
P(20,30) 
$

$
\theta = 15^\circ
$

P akhir
$
P(?,?)
$

In [ ]:
import numpy as np
theta = 15.0
x = 20
y = 30
P = np.array([[x],
             [y]])
print("P = \n",P)

#mengubah theta menjadi derajat
theta = theta / 180 * np.pi
print("Theta dalam radian = ",theta)

#merotasi matriks
rot = np.array([[np.cos(theta), -np.sin(theta)],
               [np.sin(theta), np.cos(theta)]])
print("Rotasi matriks = \n", rot)

#mengalikan matriks hasil rotasi dengan nilai P awal untuk memperoleh posisi akhir
P2 = rot.dot(P)
x2 = P2[0,0]
y2 = P2[1,0]
print("\nHasil akhir dari P', x', y' adalah: ")
print("P' = \n", P2)
print("x' = ",x2)
print("y' = ",y2)

P = 
 [[20]
 [30]]
Theta dalam radian =  0.2617993877991494
Rotasi matriks = 
 [[ 0.96592583 -0.25881905]
 [ 0.25881905  0.96592583]]

Hasil akhir dari P', x', y' adalah: 
P' = 
 [[11.55394517]
 [34.15415569]]
x' =  11.553945172705744
y' =  34.15415569072246


### 2
P akhir $P(10,30)$ 

$\theta = 78^\circ$

P awal $P(?,?)$

In [ ]:
import numpy as np
theta = 78.0
x2 = 10
y2 = 30
P2 = np.array([[x2],
              [y2]]) #Posisi Akhir P'
print("P' = \n" ,P2)

theta = theta / 180 * np.pi
print("Theta dalam radian = " ,theta)

rot = np.array([[np.cos(theta), -np.sin(theta)],
               [np.sin(theta), np.cos(theta)]])
print("Matriks rotasi: \n" ,rot)
rot = np.linalg.inv(rot)
print("Invers Matriks rotasi: \n" ,rot)

P = rot.dot(P2)
x = P[0,0]
y = P[1,0]
print("\nHasil awal dari P, x, y adalah: ")
print("P = \n" ,P)
print("x = " ,x)
print("y = " ,y)

P' = 
 [[10]
 [30]]
Theta dalam radian =  1.3613568165555772
Matriks rotasi: 
 [[ 0.20791169 -0.9781476 ]
 [ 0.9781476   0.20791169]]
Invers Matriks rotasi: 
 [[ 0.20791169  0.9781476 ]
 [-0.9781476   0.20791169]]

Hasil awal dari P, x, y adalah: 
P = 
 [[31.42354493]
 [-3.54412528]]
x =  31.42354493019176
y =  -3.54412528280528


### 3
P awal
$
P(20,30) 
$

$
\theta = 15^\circ
$

Berputar Kembali ke
$
\theta = -80^\circ
$

P akhir
$
P(?,?)
$

In [ ]:
import numpy as np
theta = 15.0
x = 20
y = 30
P = np.array([[x],
             [y]])
print("P = \n",P)
print("Theta awal = ", theta)
theta = theta / 180 * np.pi
print("Theta dalam radian = ",theta)
rot = np.array([[np.cos(theta), -np.sin(theta)],
               [np.sin(theta), np.cos(theta)]])
print("Rotasi matriks = \n", rot)
P1 = rot.dot(P)
x1 = P1[0,0]
y1 = P1[1,0]
print("P' = \n", P1)
print("x' = ",x1)
print("y' = ",y1)

P2 = np.array([[x1], 
               [y1]])
print("\nTitik P Baru = \n",P2)
theta = -80.0
print("Berputar lagi ke = ",theta)
theta = theta / 180 * np.pi
print("Theta dalam radian = ",theta)
rot = np.array([[np.cos(theta), -np.sin(theta)],
               [np.sin(theta), np.cos(theta)]])
print("Rotasi matriks berputar lagi = \n", rot)
P3 = rot.dot(P2)
x3 = P3[0,0]
y3 = P3[1,0]
print("\nHasil akhir dari P', x', y' adalah: ")
print("P' = \n", P3)
print("x' = ",x3)
print("y' = ",y3)

P = 
 [[20]
 [30]]
Theta awal =  15.0
Theta dalam radian =  0.2617993877991494
Rotasi matriks = 
 [[ 0.96592583 -0.25881905]
 [ 0.25881905  0.96592583]]
P' = 
 [[11.55394517]
 [34.15415569]]
x' =  11.553945172705744
y' =  34.15415569072246

Titik P Baru = 
 [[11.55394517]
 [34.15415569]]
Berputar lagi ke =  -80.0
Theta dalam radian =  -1.3962634015954636
Rotasi matriks berputar lagi = 
 [[ 0.17364818  0.98480775]
 [-0.98480775  0.17364818]]

Hasil akhir dari P', x', y' adalah: 
P' = 
 [[35.64159885]
 [-5.44760789]]
x' =  35.641598845913485
y' =  -5.447607888512015


### 4
P akhir $P(1,3)$ 

$\theta = 60^\circ$

Berputar lagi ke $\theta = -30^\circ$

P awal $P(?,?)$

In [ ]:
import numpy as np
theta = 60.0
x2 = 1
y2 = 3
P2 = np.array([[x2],
              [y2]]) #Posisi Akhir P'
print("P' = \n" ,P2)
print("Theta awal = ",theta)
theta = theta / 180 * np.pi
print("Theta dalam radian = " ,theta)
rot = np.array([[np.cos(theta), -np.sin(theta)],
               [np.sin(theta), np.cos(theta)]])
print("Matriks rotasi: \n" ,rot)
rot = np.linalg.inv(rot)
print("Invers Matriks rotasi: \n" ,rot)
P = rot.dot(P2)
x = P[0,0]
y = P[1,0]
print("P = \n" ,P)
print("x = " ,x)
print("y = " ,y)

P1 = np.array([[x], 
               [y]])
print("\nTitik P baru = \n", P1)
theta = -30.0
print("Berputar lagi = ",theta)
theta = theta / 180 * np.pi
print("Theta dalam radian = " ,theta)
rot = np.array([[np.cos(theta), -np.sin(theta)],
               [np.sin(theta), np.cos(theta)]])
print("Matriks rotasi: \n" ,rot)
rot = np.linalg.inv(rot)
print("Invers Matriks rotasi: \n" ,rot)

P3 = rot.dot(P1)
x = P3[0,0]
y = P3[1,0]
print("\nHasil awal dari P, x, y adalah: ")
print("P = \n" ,P3)
print("x = " ,x)
print("y = " ,y)

P' = 
 [[1]
 [3]]
Theta awal =  60.0
Theta dalam radian =  1.0471975511965976
Matriks rotasi: 
 [[ 0.5       -0.8660254]
 [ 0.8660254  0.5      ]]
Invers Matriks rotasi: 
 [[ 0.5        0.8660254]
 [-0.8660254  0.5      ]]
P = 
 [[3.09807621]
 [0.6339746 ]]
x =  3.098076211353316
y =  0.633974596215562

Titik P baru = 
 [[3.09807621]
 [0.6339746 ]]
Berputar lagi =  -30.0
Theta dalam radian =  -0.5235987755982988
Matriks rotasi: 
 [[ 0.8660254  0.5      ]
 [-0.5        0.8660254]]
Invers Matriks rotasi: 
 [[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]

Hasil awal dari P, x, y adalah: 
P = 
 [[2.3660254 ]
 [2.09807621]]
x =  2.366025403784439
y =  2.098076211353316
